---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "default"
  name: datacrapper-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datacrapper-role-cluster
rules:
  - apiGroups: [helm.toolkit.fluxcd.io]
    resources: [helmreleases]
    verbs: [list, watch, get]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "default"
  name: datascrapper-role-namespaced
rules:
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [create]
  - apiGroups: [""]
    resources: [pods, persistentvolumeclaims]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datacrapper-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datacrapper-role-cluster
subjects:
  - kind: ServiceAccount
    name: datacrapper-account
    namespace: "default"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "default"
  name: datacrapper-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: datacrapper-role-namespaced
subjects:
  - kind: ServiceAccount
    name: datacrapper-account
