repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=3000']
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: ['--unsafe', '--allow-multiple-documents']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: git@github.com:antonbabenko/pre-commit-terraform.git
    rev: v1.99.5
    hooks:
      - id: terraform_fmt
        exclude: "components/terraform/modules/aws/_template/"
      - id: terraform_tflint
        exclude: "components/terraform/modules/aws/_template/|components/terraform/bundles/"
        args:
          - --arg=--minimum-failure-severity=error

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
