---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view  # read-only доступ ко всем ресурсам
subjects:
  - kind: ServiceAccount
    name: backstage
    namespace: default
